### ISSUE TITLE
Size of colourpicker

### ISSUE THREAD

**Issue by ray73864** [mjolnic/bootstrap-colorpicker#84]
Is there any way to increase the size of the colour picker itself?

I looked at the code and saw a bunch of <div> statements for defining the template itself, but couldn't see how i could increase the size of the picker using that.

**Comment by minddust** [comment]
you just need to adjust the coordinates (manually) for a quick - non generic - solution. 

e.g. double the size:

**css**
```css
.colorpicker-saturation {
  width: 200px;
  height: 200px;
  ...
}
.colorpicker-hue,
.colorpicker-alpha {
  width: 25px;
  height: 200px;
  ...
}
```

**js**
```
$colorpicker.colorpicker({
    sliders: {
        saturation: {
            maxLeft: 200,
            maxTop: 200,
            callLeft: "setSaturation",
            callTop: "setBrightness"
        },
        hue: {
            maxLeft: 0,
            maxTop: 200,
            callLeft: false,
            callTop: "setHue"
        },
        alpha: {
            maxLeft: 0,
            maxTop: 200,
            callLeft: false,
            callTop: "setAlpha"
        }
    }
});
```

live demo here: [https://www.pixelmaker.io/](https://www.pixelmaker.io/)
